name: Security CI
on: [push]
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: |
          echo "=== Security Scan Summary ===" 
          npm audit --audit-level=high
          echo "---------------------------"
          npm outdated || echo "Outdated packages (non-blocking): See above."

      